'use client';

import Link from 'next/link';
import { useState, useCallback, useEffect } from 'react';
import { AlertTriangle, TrendingUp, Check, Loader, Users, Heart, Search } from 'lucide-react';
import AgentPageLayout from '@/components/AgentPageLayout';
import ScoreGauge from '@/components/ScoreGauge';
import type { CustomerSuccessResult } from '@/types';

const COLOR = '#ff9500';

const STEPS = [
  { name: 'Loading customer profile', output: 'Customer record, company, and subscription plan loaded from CRM' },
  { name: 'Calculating health score', output: 'LLM computed health score from engagement, support, and usage data' },
  { name: 'Assessing churn risk', output: 'Churn risk level and probability estimated from health indicators' },
  { name: 'Analyzing engagement patterns', output: 'Login frequency, feature adoption, and last activity analyzed' },
  { name: 'Identifying upsell opportunities', output: 'Upsell signals identified from usage patterns and plan limits' },
  { name: 'Generating action recommendations', output: 'Priority action items generated by LLM · Retention playbook applied' },
  { name: 'Publishing alerts if at-risk', output: 'Churn alert published to Customer Success team if risk threshold met' },
];

interface CustomerOption {
  id: string;
  company_name: string;
  plan: string;
  mrr: number;
  health_score: number;
  churn_risk: string;
}

const CHURN_COLOR: Record<string, string> = {
  low: '#34c759', medium: '#ff9500', high: '#ff6b00', critical: '#ff3b30',
};
const churnBadge: Record<string, string> = {
  low: 'badge-green', medium: 'badge-orange', high: 'badge-red', critical: 'badge-red',
};

export default function CustomersPage() {
  const [result, setResult]         = useState<CustomerSuccessResult | null>(null);
  const [isComplete, setIsComplete] = useState(false);
  const [error, setError]           = useState<string | null>(null);

  // Customer list from CRM DB
  const [customers, setCustomers]         = useState<CustomerOption[]>([]);
  const [customersLoading, setCustomersLoading] = useState(true);
  const [selectedCustomer, setSelectedCustomer] = useState<CustomerOption | null>(null);

  useEffect(() => {
    fetch('http://localhost:8000/api/customers/list')
      .then(r => r.ok ? r.json() : [])
      .then((data: CustomerOption[]) => {
        setCustomers(data);
      })
      .catch(() => {})
      .finally(() => setCustomersLoading(false));
  }, []);

  const handleRun = useCallback(async (formData: Record<string, string>) => {
    const targetId = selectedCustomer?.id || formData.customer_id;
    const targetName = selectedCustomer?.company_name || formData.company_name || 'Unknown Customer';

    setError(null);
    setIsComplete(false);

    if (!targetId) {
      setError('Please select a customer from the list above.');
      setIsComplete(true);
      return null;
    }

    const res = await fetch(`http://localhost:8000/api/agents/monitor-customer/${targetId}/sync`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({}),
    }).then(r => r.ok ? r.json() : null).catch(() => null);

    if (res) {
      const healthScore = res.health_score ?? (selectedCustomer?.health_score || 50);
      const churnLevel  = res.churn_risk?.level ?? (selectedCustomer?.churn_risk || 'medium');
      setResult({
        customer_id: targetId,
        company_name: targetName,
        health_score: healthScore,
        churn_risk: {
          level: (churnLevel as 'low' | 'medium' | 'high' | 'critical'),
          probability: res.churn_risk?.probability ?? Math.max(0, 100 - healthScore),
          factors: res.churn_risk?.factors ?? [],
        },
        engagement: res.engagement ?? {
          logins_per_week: 0,
          feature_adoption_pct: 0,
          last_login: '—',
        },
        upsell_opportunities: res.opportunities ?? res.upsell_opportunities ?? [],
        recommended_actions: res.recommended_actions ?? [],
      });
      setIsComplete(true);
      // Return real execution steps for WorkflowSteps replay
      return res.execution_steps ?? null;
    } else {
      setError('Agent call failed — ensure the backend is running and try again.');
      setIsComplete(true);
      return null;
    }
  }, [selectedCustomer]);

  const customerSelector = (
    <div className="apple-card mb-4 overflow-hidden" style={{ padding: 0 }}>
      <div className="px-4 py-3 border-b flex items-center justify-between bg-[var(--bg-secondary)]" style={{ borderColor: 'var(--border-primary)' }}>
        <div className="flex items-center gap-2">
          <Heart size={14} color={COLOR} />
          <h3 className="font-700 text-sm" style={{ fontWeight: 700, color: 'var(--text-primary)' }}>
            Customers {!customersLoading && <span className="ml-1 opacity-60 font-medium">({customers.length} found)</span>}
          </h3>
        </div>
        {!customersLoading && <div className="text-[10px] font-bold text-[var(--text-tertiary)] uppercase tracking-widest text-right" style={{ minWidth: 40 }}></div>}
      </div>
      
      {customersLoading ? (
        <div className="flex items-center gap-2 p-6 justify-center">
          <Loader size={18} color={COLOR} className="animate-spin" />
          <span className="text-xs font-medium" style={{ color: 'var(--text-secondary)' }}>Loading portfolio…</span>
        </div>
      ) : customers.length === 0 ? (
        <div className="p-8 text-center bg-[var(--bg-tertiary)]">
          <p className="text-xs font-medium mb-3" style={{ color: 'var(--text-tertiary)' }}>No production customers found.</p>
          <Link href="/sources">
            <button className="btn-primary text-[10px] py-1 px-3">Go to Source Systems</button>
          </Link>
        </div>
      ) : (
        <div className="max-h-72 overflow-y-auto custom-scrollbar">
          {customers.map(c => (
            <button
              key={c.id}
              onClick={() => setSelectedCustomer(c)}
              className="w-full text-left px-4 py-3 transition-colors border-b last:border-0 hover:bg-[var(--bg-tertiary)]"
              style={{
                borderColor: 'var(--border-secondary)',
                background: selectedCustomer?.id === c.id ? `${COLOR}08` : 'transparent',
              }}>
              <div className="flex items-center gap-3">
                <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0`} 
                     style={{ background: `${CHURN_COLOR[c.churn_risk]}15`, border: `1px solid ${CHURN_COLOR[c.churn_risk]}30` }}>
                  <Heart size={14} style={{ color: CHURN_COLOR[c.churn_risk] }} />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-0.5">
                    <span className="text-[13px] font-700 truncate" style={{ color: 'var(--text-primary)', fontWeight: 700 }}>
                      {(c.company_name || 'Unknown').replace(/([a-f0-9]{4})[a-f0-9-]{28,}/gi, '$1')}
                    </span>
                    {selectedCustomer?.id === c.id && <div className="w-1.5 h-1.5 rounded-full" style={{ background: COLOR }} />}
                  </div>
                  <div className="flex items-center gap-2 overflow-hidden">
                    <span className="text-[9px] font-mono font-bold uppercase tracking-wider px-1.5 py-0.5 rounded" style={{ background: 'var(--bg-tertiary)', color: 'var(--text-tertiary)' }}>#{c.id?.slice(0,4).toUpperCase()}</span>
                    <span className="text-[10px] font-bold uppercase tracking-wider" style={{ color: CHURN_COLOR[c.churn_risk] }}>{c.churn_risk} risk</span>
                    <span className="text-[10px] text-[var(--text-tertiary)]">·</span>
                    <span className="text-[11px] font-semibold" style={{ color: 'var(--text-secondary)' }}>${(c.mrr ?? 0).toLocaleString()}/mo</span>
                  </div>
                </div>
                 <div className="text-right flex-shrink-0" style={{ minWidth: 40 }}>
                    <div className="text-[1.5px] w-1.5 h-1.5 rounded-full" style={{ background: selectedCustomer?.id === c.id ? COLOR : 'transparent' }} />
                 </div>
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  );

  return (
    <div className="max-w-[1400px]">
      <AgentPageLayout
        agentId="CustomerSuccessAgent"
        agentName="Customer Success"
        agentDescription="Monitors customer health from CRM data, detects churn risk, analyzes engagement metrics, and generates AI-powered retention recommendations."
        agentColor={COLOR}
        agentEmoji="🎉"
        formFields={[
          { key: 'customer_id', label: 'Customer ID (Optional)', placeholder: '12345...' },
          { key: 'company_name', label: 'Company Name', placeholder: 'Acme Corp' }
        ]}
        defaultValues={{ customer_id: '', company_name: '' }}
        examples={[]}
        steps={STEPS}
        onRun={handleRun}
        error={error}
        isComplete={isComplete}
        isReady={!!selectedCustomer}
        externalFillValues={selectedCustomer ? {
          customer_id: selectedCustomer.id,
          company_name: selectedCustomer.company_name,
        } : null}
        headerExtra={customerSelector}
        resultNode={result && (
          <div className="space-y-4">
            <div className="apple-card py-2 px-3" style={{ borderColor: `${COLOR}30` }}>
              <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>Analyzing</p>
              <p className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>{result.company_name}</p>
            </div>

            <div className="apple-card flex gap-6 items-center">
              <ScoreGauge score={result.health_score} size={110} label="Health" />
              <div className="flex-1">
                <p className="text-xs font-semibold uppercase tracking-wide mb-2" style={{ color: 'var(--text-tertiary)', letterSpacing: '0.06em' }}>Churn Risk</p>
                <div className="flex items-center gap-3 mb-2">
                  <span className={`badge ${churnBadge[result.churn_risk.level]}`}
                    style={{ fontSize: 16, padding: '6px 16px', fontWeight: 700, letterSpacing: '0.05em' }}>
                    {result.churn_risk.level.toUpperCase()}
                  </span>
                  <span style={{ fontSize: 28, fontWeight: 800, color: CHURN_COLOR[result.churn_risk.level] }}>
                    {result.churn_risk.probability}%
                  </span>
                </div>
                <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>Churn probability this quarter</p>
              </div>
            </div>

            <div className="apple-card">
              <p className="text-xs font-semibold uppercase tracking-wide mb-3" style={{ color: 'var(--text-tertiary)', letterSpacing: '0.06em' }}>Engagement Metrics</p>
              <div className="grid grid-cols-3 gap-3">
                <div className="text-center p-3 rounded-xl" style={{ background: 'var(--bg-input)' }}>
                  <p style={{ fontSize: 22, fontWeight: 800, color: '#ff3b30' }}>{result.engagement.logins_per_week}/wk</p>
                  <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>Logins</p>
                </div>
                <div className="text-center p-3 rounded-xl" style={{ background: 'var(--bg-input)' }}>
                  <p style={{ fontSize: 22, fontWeight: 800, color: '#ff9500' }}>{result.engagement.feature_adoption_pct}%</p>
                  <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>Feature Adoption</p>
                </div>
                <div className="text-center p-3 rounded-xl" style={{ background: 'var(--bg-input)' }}>
                  <p style={{ fontSize: 16, fontWeight: 700, color: 'var(--text-primary)' }}>{result.engagement.last_login}</p>
                  <p className="text-xs" style={{ color: 'var(--text-tertiary)' }}>Last Login</p>
                </div>
              </div>
            </div>

            {result.churn_risk.factors?.length > 0 && (
              <div className="apple-card">
                <p className="text-xs font-semibold uppercase tracking-wide mb-3" style={{ color: 'var(--text-tertiary)', letterSpacing: '0.06em' }}>Negative Churn Signals</p>
                <div className="space-y-2">
                  {result.churn_risk.factors.map((s, i) => (
                    <div key={i} className="flex items-start gap-2 p-2 rounded-lg"
                      style={{ background: 'var(--bg-tertiary)', border: '1px solid var(--border-secondary)' }}>
                      <AlertTriangle size={14} color="#ff3b30" style={{ flexShrink: 0, marginTop: 2 }} />
                      <span className="text-sm" style={{ color: 'var(--text-secondary)' }}>{s}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {result.upsell_opportunities?.length > 0 && (
              <div className="apple-card">
                <p className="text-xs font-semibold uppercase tracking-wide mb-3" style={{ color: 'var(--text-tertiary)', letterSpacing: '0.06em' }}>Upsell Opportunities</p>
                <div className="space-y-3">
                  {result.upsell_opportunities.map((u, i) => (
                    <div key={i} className="p-3 rounded-xl" style={{ background: 'var(--bg-input)', border: '1px solid var(--border-secondary)' }}>
                      <div className="flex items-center gap-2 mb-1">
                        <span className="badge badge-teal">{u.type}</span>
                        <span className="text-xs ml-auto" style={{ color: 'var(--text-tertiary)' }}>Confidence: {Math.round((u.confidence ?? 0) * 100)}%</span>
                        <span className="text-xs font-semibold" style={{ color: COLOR }}>+${u.estimated_value}/mo</span>
                      </div>
                      <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>{u.description}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {result.recommended_actions?.length > 0 && (
              <div className="apple-card">
                <p className="text-xs font-semibold uppercase tracking-wide mb-3" style={{ color: 'var(--text-tertiary)', letterSpacing: '0.06em' }}>Recommended Actions</p>
                <div className="space-y-2">
                  {result.recommended_actions.map((a, i) => (
                    <div key={i} className="flex items-start gap-3 p-3 rounded-xl"
                      style={{
                        background: a.priority === 'high' ? 'rgba(255,59,48,0.05)' : 'var(--bg-input)',
                        border: `1px solid ${a.priority === 'high' ? 'rgba(255,59,48,0.15)' : 'var(--border-secondary)'}`,
                      }}>
                      <span className={`badge badge-${a.priority === 'high' ? 'red' : a.priority === 'medium' ? 'orange' : 'gray'} flex-shrink-0`}>{a.priority}</span>
                      <span className="text-sm flex-1" style={{ color: 'var(--text-secondary)' }}>{a.action}</span>
                      {a.due_date && <span className="text-xs flex-shrink-0" style={{ color: 'var(--text-tertiary)' }}>{a.due_date}</span>}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      />
    </div>
  );
}
